# Generated by Django 6.0.4 on 2026-05-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        help_text="Введите дату последнего изменения",
                        max_length=10,
                        verbose_name="Дата последнего изменения",
                    ),
                ),
                (
                    "description",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите описание продукта",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo",
                        to="catalog.category",
                        verbose_name="Описание продукта",
                    ),
                ),
            ],
        ),
    ]
