# Generated by Django 6.0.4 on 2026-05-07 20:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name", "description"],
                "verbose_name": "Название категории продукта",
                "verbose_name_plural": "Названия категорий продуктов",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "price", "updated_at", "created_at"],
                "verbose_name": "Наименование продукта",
                "verbose_name_plural": "Наименования продуктов",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание категории продукта",
                null=True,
                verbose_name="Описание категории продукта",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="Без названия",
                help_text="Введите название категории продукта",
                max_length=100,
                verbose_name="Название категории продукта",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите категорию продукта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photo",
                to="catalog.category",
                verbose_name="Категория продукта",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Введите дату создания",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(
                default="Новый продукт",
                help_text="Введите наименование продукта",
                max_length=100,
                verbose_name="Наименование продукта",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото продукта",
                null=True,
                upload_to="catalog/photo/",
                verbose_name="Фото продукта",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                default=0,
                help_text="Введите цену продукта",
                verbose_name="Цена продукта",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание продукта",
                null=True,
                verbose_name="Описание продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Введите дату последнего изменения",
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
