# Generated by Django 6.0.4 on 2026-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="Название продукта",
                help_text="Введите название категории продукта",
                max_length=100,
                verbose_name="Название категории продукта",
            ),
        ),
    ]
