# Generated by Django 6.0.4 on 2026-05-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="Введите название",
                help_text="Введите название категории продукта",
                max_length=100,
                verbose_name="Название категории продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                default=0,
                help_text="Введите цену продукта",
                verbose_name="Цена продукта",
            ),
        ),
    ]
