# Generated by Django 6.0.4 on 2026-05-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_blog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
